#define WSSID "REPLACE WITH YOUR WIFI SSID" 
#define WPASS "REPLACE WITH YOUR WIFI PASS" 

#define NETSKEY	"REPLACE WITH YOUR NETWORK SESSION KEY"
#define	APPSKEY	"REPLACE WITH YOUR APPLICATION SESSION KEY"
#define	DEVADDR	"REPLACE WITH YOUR DEVICE ADRESS"

#define	NETSKEYDRAG "REPLACE WITH YOUR NETWORK SESSION KEY"
#define	APPSKEYDRAG "REPLACE WITH YOUR APPLICATION SESSION KEY"
#define	DEVADDRDRAG "REPLACE WITH YOUR DEVICE ADRESS"

#define DEVICE_ID "REPLACE WITH YOUR DEVICE ID"
#define	ACCESS_KEY "REPLACE WITH YOUR ACCESS KEY"
#define	ACCESS_SECRET "REPLACE WITH YOUR ACCES SECRET"
