#define WIFIAP "ADD YOUR WIFI SSID HERE"
#define WIFIPASS "ADD YOUR WIFI PASS HERE"

#define THINGSBOARDSERVER "THINGS BOARD SERVER"
#define	THINGSBOARDCLIENTID "THINGS BOARD DEVICE CLIENT ID"
#define	THINGSBOARDTOKEN "THINGS BOARD DEVICE TOKEN"

// THINGS BOARD EXAMPLE
// #define THINGSBOARDSERVER "demo.thingsboard.io"
// #define	THINGSBOARDCLIENTID "443bc870-c952-11e8-8304-d11ebf0ac14e"
// #define	THINGSBOARDTOKEN "hhbsU1Lwrghr4FzAWVkN"